name: Test Project

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Success message
        run: echo "Layihe ugurla yoxlandi!"
        
